name: eso
description: 亦搜，亦看，亦闻
publish_to: none
version: 1.23.6+12306
homepage: https://github.com/mabdc/eso
author: mabdc

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  about: ^2.1.3
  archive: ^3.4.2
  # audioplayers: ^3.0.1
  battery_plus: ^5.0.3
  cached_network_image: ^3.2.3
  device_info: ^2.0.3
  dlna:
    path: modules/DLNA-Dart
  encrypt: ^5.0.1
  equatable: ^2.0.5
  fast_gbk: ^1.0.0
  filesystem_picker: ^4.1.0
  floor: ^1.4.2
  webview_windows: ^0.4.0
  # xpath_selector: ^2.2.4
  xpath_selector:
    path: modules/xpath_selector
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_highlight: ^0.7.0
  flutter_localizations:
    sdk: flutter
  flutter_qjs: ^0.3.7
  # text_to_speech: ^0.2.3
  flutter_tts: ^4.0.2
  flutter_webview:
    path: modules/flutter_webview
  html: ^0.15.3
  http: ^0.13.5
  image_gallery_saver: ^2.0.3
  intl: ^0.17.0
  json_path: ^0.4.4
  matrix_gesture_detector: ^0.2.0-nullsafety.1
  oktoast: ^3.3.2+1
  outline_material_icons: ^1.0.0
  package_info_plus: ^1.4.2
  path_provider: ^2.0.15
  permission_handler: ^11.0.1
  photo_view: ^0.15.0
  provider: ^6.1.2
  device_display_brightness: ^0.0.6
  scrollable_positioned_list: ^0.3.8
  share_plus: ^4.5.3
  shared_preferences: ^2.2.0
  sqflite_common_ffi: ^2.2.5
  text_composition:
    path: modules/text_composition
  url_launcher: ^6.1.11
  uuid: ^4.1.0
  webdav:
    # git: https://github.com/timestee/dart-webdav
    path: modules/dart-webdav
  webview_flutter:
    path: modules/webview_flutter
  http_multi_server: ^3.2.1
  window_manager: ^0.3.7
  hive_flutter: ^1.1.0
  # explorer: ^2.1.0
  epubx: ^3.0.0
  # win32: ^2.4.2
  file_picker: ^4.6.1
  flutter_inappwebview: ^5.8.0
  flutter_hooks: ^0.20.5
  hetu_script_flutter: ^0.1.0+2
  flutter_displaymode: ^0.6.0
  uni_links: ^0.5.1
  waterfall_flow: ^3.0.3
  flutter_lyric: ^2.0.4+6
  just_audio: ^0.9.37
  dio: ^5.4.3+1
  # just_audio_background: ^0.0.1-beta.10
  just_audio_windows: ^0.2.1
  just_audio_mpv: ^0.1.7
  audio_service: ^0.18.13
  auto_orientation: ^2.3.1
  video_player: ^2.7.0
  flutter_screenutil: ^5.7.0
  fluttertoast: ^8.2.5
  huijing_ads_plugin:
    path: modules/huijing_ads_plugin/


dev_dependencies:
  build_runner: ^2.3.3
  floor_generator: ^1.4.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - player.html
    - CHANGELOG.md
    - README.md
    - LICENSE
    - lib/assets/
    - assets/bg/
    - assets/ba/
    - assets/JsDecoder.js
  fonts:
    - family: fonticons
      fonts:
        - asset: fonts/fonticons.ttf

    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
